controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


joint_trajectory_controller:
  ros__parameters:
    joints:
      # Wrist / palm chain
      - forearm:1--base:1
      - palm_axis:1--forearm:1
      - palmL:1--palm_axis:1

      # Thumb
      - Thumb_axis--palmL:1
      - Thumb_Methacarpal--Thumb_axis
      - Thumb_Proximal--Thumb_Methacarpal
      - Thumb_Distal--Thumb_Proximal

      # Index
      - Index_Proximal--palmL:1
      - Index_Middle--Index_Proximal
      - Index_Distal--Index_Middle

      # Middle
      - Middle_Proximal--palmL:1
      - Middle_Middle--Middle_Proximal
      - Middle_Distal--Middle_Middle

      # Ring
      - Ring_Proximal--palmL:1
      - Ring_Middle--Ring_Proximal
      - Ring_Distal--Ring_Middle

      # Small
      - Small_Proximal--palmL:1
      - Small_Middle--Small_Proximal
      - Small_Distal--Small_Middle

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
