controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    allow_partial_joints_goal: false
    
    joints:
      # Wrist / palm chain
      - forearm:1--base:1
      - palm_axis:1--forearm:1
      - palmL:1--palm_axis:1

      # Thumb
      - Thumb_axis--palmL:1
      - Thumb_Methacarpal--Thumb_axis

      # Index
      - Index_Proximal--palmL:1

      # Middle
      - Middle_Proximal--palmL:1

      # Ring and Small
      - Ring_Proximal--palmL:1

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
